### Testar função de saúde (health)

GET http://localhost:3000/health

### Testar função de signin

POST http://localhost:3000/signin
Content-Type: application/json

{
  "username": "usuario",
  "password": "senha"
}

### Testar função de signup

POST http://localhost:3000/signup
Content-Type: application/json

{
  "goal": "lose",
  "birthGender": "male",
  "birthDate": "2000-01-01",
  "height": 180,
  "weight": 70,
  "activityLevel": 3,
  "account": {
    "name": "Matheus",
    "email": "matheus@example.com",
    "password": "senha1234"
  }
}

### Testar função de signin com erro

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "matheus@example.com",
  "password": "senha_errada"
}