# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: patitowdevfoodiary
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

provider:
  name: aws
  region: us-east-2
  runtime: nodejs22.x
  architecture: arm64

# ESBuild
build:
  esbuild:
    minify: true
    sourcemap: false

# Indivudual lambda function archives
package: 
  individually: true

functions:
  health:
    handler: src/health.handler
    events:
      - httpApi:
          path: /health
          method: get

  signin:
    handler: src/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post
  signup:
    handler: src/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
